### ISSUE TITLE
перебор значений енумов 1

### ISSUE THREAD

**Issue by maksgir** [G0ld3nDr4g0n3301/ITMO_Programming_Labs#1]
https://github.com/G0ld3nDr4g0n3301/ITMO_Programming_Labs/blob/2eec69d6855474dd1590b1f6efb5e178dfdc683e/lab4/src/beds/Vegetable.java#L14
а что будет если овощей будет 100500? давай-ка подумаем что с этим можно сделать

**Comment by G0ld3nDr4g0n3301** [comment]
Ну, я добавил экземплярам энама метод getIncreasedVolume. Он высчитывает для каждого овоща свою формулу. И мы просто используем на экземпляре метод. Единственный минус - нам надо будет прописывать формулу увеличения овоща для каждого нового овоща,но терпимо.
