### ISSUE TITLE
а зачем?)

### ISSUE THREAD

**Issue by maksgir** [G0ld3nDr4g0n3301/ITMO_Programming_Labs#2]
https://github.com/G0ld3nDr4g0n3301/ITMO_Programming_Labs/blob/2eec69d6855474dd1590b1f6efb5e178dfdc683e/lab4/src/beds/Vegetable.java#L49C42-L49C42
зочем тут /1 ?

**Comment by G0ld3nDr4g0n3301** [comment]
Потому что waterLevel это double. А мне нужна просто его целая часть, поэтому я делю её на 1. А конвертирую в инт - чтобы было удобно сравнивать(иначе не получилось  бы просто сравнить свитч кейсом из-за особенностей представления чисел с плавающей точкой в памяти,пришлось бы через if-else и equals, а это не так красиво.)

**Comment by G0ld3nDr4g0n3301** [comment]
Вы правы,юслес. Убрал.
