### ISSUE TITLE
инкапсуляция 

### ISSUE THREAD

**Issue by maksgir** [G0ld3nDr4g0n3301/ITMO_Programming_Labs#3]
https://github.com/G0ld3nDr4g0n3301/ITMO_Programming_Labs/blob/2eec69d6855474dd1590b1f6efb5e178dfdc683e/lab4/src/beds/VegetableType.java#L9 
где модификаторы??????

**Comment by G0ld3nDr4g0n3301** [comment]
Сделал приват и добавил геттер
