### ISSUE TITLE
инкапсуляцияяяяя

### ISSUE THREAD

**Issue by maksgir** [G0ld3nDr4g0n3301/ITMO_Programming_Labs#4]
https://github.com/G0ld3nDr4g0n3301/ITMO_Programming_Labs/blob/2eec69d6855474dd1590b1f6efb5e178dfdc683e/lab4/src/misc/Basket.java#L9

пачему паблик??

**Comment by G0ld3nDr4g0n3301** [comment]
Это всё Черный кодер опять... Хотя в данной ситуации виновна моя лень, писать все эти геттеры-сеттеры очень утомительно. Исправил.(не лень,а ошибку)
