### ISSUE TITLE
логика

### ISSUE THREAD

**Issue by maksgir** [G0ld3nDr4g0n3301/ITMO_Programming_Labs#5]
https://github.com/G0ld3nDr4g0n3301/ITMO_Programming_Labs/blob/2eec69d6855474dd1590b1f6efb5e178dfdc683e/lab4/src/shorties/Fix.java#L19
по твоей логике этот карапуз каждый раз когда вызывается метод **takeBroom** создает новую метлу. ты также делаешь?

**Comment by G0ld3nDr4g0n3301** [comment]
Нет,я просто не могу придумать для своего текста юс-кейс для анонимных классов. Я добавил провеку на двойное взятие метлы,на всякий случай,хотя суть это не исправит. У меня к сожалению здесь не хватает фантазии,да и вообще мне тяжело придумать нормальный пример использования анонимных классов в какой-то реал-лайф ситуации. Они хороши,если всё очень просто и пример несложный, а иначе они будут захламлять код своим объёмом. Пока не закрываю ишью, но сделать я особо ничего не могу здесь из за creativity-issue.

**Comment by G0ld3nDr4g0n3301** [comment]
Мне как-то дискомфортно,когда открытые ишью висят,так что я закрою,если вы не против.

**Comment by G0ld3nDr4g0n3301** [comment]
Теперь класс Trap - анонимный и используется только в методе main один раз.
