### ISSUE TITLE
фикси

### ISSUE THREAD

**Issue by maksgir** [G0ld3nDr4g0n3301/ITMO_Programming_Labs#6]
https://github.com/G0ld3nDr4g0n3301/ITMO_Programming_Labs/blob/2eec69d6855474dd1590b1f6efb5e178dfdc683e/lab4/src/shorties/Harvester.java#L44
всё.

**Comment by G0ld3nDr4g0n3301** [comment]
Добавил грядкам выбрасывание исключения,если создаётся поле с шириной 0 или длиной 0.
