### ISSUE TITLE
а зачем?)

### ISSUE THREAD

**Issue by maksgir** [G0ld3nDr4g0n3301/ITMO_Programming_Labs#7]
https://github.com/G0ld3nDr4g0n3301/ITMO_Programming_Labs/blob/2eec69d6855474dd1590b1f6efb5e178dfdc683e/lab4/src/shorties/Shorty.java#L25
почему протектед

**Comment by G0ld3nDr4g0n3301** [comment]
Я... Не помню... Это очень странно,учитывая,что я ничего от ноги не наследую,а геттер уже написан,так что моей ленью это не объяснить... Я знаю,кто мог такое сделать! Я слышал легенду о чёрном кодере,который приходит,и пишет плохой код за людей. Мне кажется это был он. Берегитесь черного кодера
P.S. пожалуйста,не надо меня отменять, тут нет никакого расизма
