### ISSUE TITLE
неправильынй иквалс 

### ISSUE THREAD

**Issue by maksgir** [G0ld3nDr4g0n3301/ITMO_Programming_Labs#8]
https://github.com/G0ld3nDr4g0n3301/ITMO_Programming_Labs/blob/2eec69d6855474dd1590b1f6efb5e178dfdc683e/lab4/src/shorties/Shorty.java#L134
а если передам нулл?

**Comment by G0ld3nDr4g0n3301** [comment]
Вы чертовски правы,забыл добавить проверку на нулл.
